---
- name: web-server confifuration
  hosts: Web-Servers
  become: true
  tasks:
    - name: ensure nginx is at the latest version
      apt:
        name: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes  # if you want to also enable nginx
        

